joint_limits:
  slider_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 0.6
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
  arm_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
